Repository CodeitSB01-06-Otboo/sb01-otboo-team6, pull requests merged in 2025-07, with the labels that each got.

#41 사용자 회원가입·로그인,JWT 인증 기능#38
  build.gradle
  src/main/java/com/codeit/sb01otbooteam06/config/SecurityConfig.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/controller/AuthController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/dto/ResetPasswordRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/dto/SignInRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/dto/TokenResponse.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/service/AuthService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/controller/UserController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/AuthorDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/ChangePasswordRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/UserCreateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/UserDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/UserListResponse.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/UserLockUpdateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/UserRoleUpdateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/UserSummary.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/entity/Role.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/entity/User.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/exception/UserNotFoundException.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/init/AdminInitializer.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/repository/UserRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/service/UserService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/service/UserServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/ErrorCode.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/GlobalExceptionHandler.java
  src/main/resources/application-dev.yml
  src/main/resources/schema.sql
Labels: ✨기능 추가

#46 SecurityConfig 전체 permitAll 임시 적용 (테스트 용도)
  src/main/java/com/codeit/sb01otbooteam06/config/SecurityConfig.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/controller/AuthController.java
Labels: ✨기능 추가

#44 feat: 피드, 좋아요, 댓글 REST API 및 도메인 계층 추가
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/controller/FeedController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/request/CommentCreateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/request/FeedUpdateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/CommentDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/CommentDtoCursorResponse.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/FeedDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/FeedDtoCursorResponse.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/entity/Comment.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/entity/Feed.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/repository/CommentRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/repository/FeedLikeRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/repository/FeedRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/CommentService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/FeedLikeService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/FeedService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/CommentServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/FeedLikeServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/FeedServiceImpl.java
Labels: ✨기능 추가

#42 Feat/39 팔로우 및 dm 서비스 구현
  build.gradle
  src/main/java/com/codeit/sb01otbooteam06/config/WebSocketConfig.java
  src/main/java/com/codeit/sb01otbooteam06/domain/dm/controller/DirectMessageController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/dm/dto/DirectMessageCreateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/dm/dto/DirectMessageDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/dm/entity/DirectMessage.java
  src/main/java/com/codeit/sb01otbooteam06/domain/dm/repository/DirectMessageRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/dm/service/DirectMessageService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/follow/controller/FollowController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/follow/dto/FollowDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/follow/entity/Follow.java
  src/main/java/com/codeit/sb01otbooteam06/domain/follow/repository/FollowRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/follow/service/FollowService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/weather/dto/WeatherDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/weather/repository/WeatherQueryRepositoryImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/weather/service/KakaoLocalClient.java
  src/main/java/com/codeit/sb01otbooteam06/domain/weather/service/WeatherService.java
Labels: ✨기능 추가

#57 feat: add ClothesFeed entity and update related mapping and services
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/entity/dto/OotdDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/controller/FeedController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/CommentDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/FeedDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/entity/ClothesFeed.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/entity/Feed.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/FeedLikeService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/FeedLikeServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/weather/mapper/WeatherDtoMapper.java
  src/main/resources/schema.sql
Labels: ♻️리팩토링

#59 추천 기능 임시 코드, PR 템플릿 파일 위치 변경
  .github/ISSUE_TEMPLATE/이슈템플릿.md
  .github/pull_request_template.md
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/RecommendationService.java
  src/main/resources/schema.sql
Labels: ✨기능 추가

#62 refactor: 구체적인 오류 발생 메제지, 피드 좋아요 기능 구현 및 주석 처리
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/CommentDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/FeedDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/CommentServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/FeedLikeServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/ErrorCode.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/GlobalExceptionHandler.java
Labels: ♻️리팩토링

#61 feat: 프로필 로직구현
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/service/AuthService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/controller/ProfileController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/dto/ProfileDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/dto/ProfileUpdateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/entity/Gender.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/entity/Profile.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/exception/ProfileNotFoundException.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/mapper/ProfileMapper.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/service/ProfileService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/storage/FileStorageService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/util/GeoUtils.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/entity/User.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/service/UserServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/ErrorCode.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/GlobalExceptionHandler.java
  src/main/resources/application-dev.yml
Labels: ✨기능 추가

#66 :recycle: dev 환경에서 DB 테이블 schema.sql 기반 생성, data.sql 데이터 추가
  src/main/resources/application-dev.yml
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: ⛅공통 코드

#68 Feat/aws #10 aws github actions CD 테스
  .aws/obtoo-task-revision1.json
  Dockerfile
Labels: 🚀배포

#72 :rocket: 브랜치 설정
  .github/workflows/aws.yml
Labels: 🚀배포

#74 feat: 피드 목록 조회 리팩토링 및 기능 확장, 페이징 및 정렬 추가
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/controller/FeedController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/CommentDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/FeedDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/entity/Feed.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/repository/FeedQueryRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/repository/FeedQueryRepositoryImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/repository/FeedRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/FeedService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/CommentServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/FeedLikeServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/ErrorCode.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/GlobalExceptionHandler.java
  src/main/resources/data.sql
Labels: ♻️리팩토링

#76 이슈템플릿업데이트
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: ⛅공통 코드

#95 S3 버킷 연결, 의상 이미지 등록 추가
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  build.gradle
  src/main/java/com/codeit/sb01otbooteam06/config/S3Config.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesService.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/ErrorCode.java
  src/main/java/com/codeit/sb01otbooteam06/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeit/sb01otbooteam06/global/s3/S3Service.java
  src/main/java/com/codeit/sb01otbooteam06/global/s3/exception/S3UploadException.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: ⛅공통 코드, ♻️리팩토링

#103 :recycle: comment 페이지네이션 버그 수정
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/entity/dto/OotdDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/CommentDtoCursorResponse.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/FeedDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/repository/CommentRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/service/impl/CommentServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/weather/dto/PrecipitationDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/weather/dto/TemperatureDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/weather/dto/WeatherSummaryDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/weather/mapper/WeatherDtoMapper.java
Labels: ♻️리팩토링

#110 임시 비밀번호 로직 및 s3 프로필 이미지 로직 개선
  build.gradle
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/dto/TokenResponse.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/entity/Profile.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/mapper/ProfileMapper.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/storage/FileStorageService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/storage/S3FileStorageService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/entity/User.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/service/UserServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/schema.sql
Labels: ♻️리팩토링

#125 :test_tube: 피드, 댓글 , 좋아요 서비스 테스트코드 작성 및 request 패턴 리팩토링
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/request/CommentCreateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/request/FeedUpdateRequest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/feed/comment/service/CommentServiceImplTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/feed/like/service/FeedLikeServiceImplTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/feed/service/FeedServiceImplTest.java
Labels: ✅테스트 코드, ♻️리팩토링

#123 feat(auth): 구글·카카오 OAuth 로그인 구현 및 JWT 연동 완료#120
  build.gradle
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/controller/AuthController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/controller/OAuthController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/dto/OAuthUserResponse.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/oauth/OAuthService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/oauth/OAuthServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/oauth/client/GoogleOAuthClient.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/oauth/client/KakaoOAuthClient.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/oauth/userinfo/GoogleUserInfo.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/oauth/userinfo/KakaoUserInfo.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/oauth/userinfo/OAuthUserInfo.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/entity/User.java
  src/main/resources/application-dev.yml
Labels: ✨기능 추가

#151 의상 추천 기능 고도화(캐시 도입) & 리팩토링, 의상 컨트롤러 테스트코드작성
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  build.gradle
  src/main/java/com/codeit/sb01otbooteam06/config/CacheConfig.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/entity/Clothes.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/entity/ClothesAttribute.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/entity/dto/ClothesAttributeDefCreateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/entity/dto/ClothesAttributeDefDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/entity/dto/ClothesUpdateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/repository/AttributeDefCustomRepositoryImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/repository/ClothesAttributeCustomRepositoryImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/repository/RecommendClothesRepository.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/AttributeDefService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesAttributeService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesCacheService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/RecommendClothesService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/RecommendService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/controller/AttributeDefControllerTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/controller/ClothesControllerTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/controller/RecommendationControllerTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/repository/AttributeDefRepositoryTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/repository/ClothesAttributeRepositoryTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesAttributeServiceTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesCacheServiceTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesServiceTest.java
  src/test/java/com/codeit/sb01otbooteam06/util/EntityProvider.java
Labels: ✨기능 추가, ✅테스트 코드, ♻️리팩토링

#153 리드미 업데이트
  README.md
Labels: ✏️문서작성

#158 :test_tube: 피드 레포지토리, 피드 컨트롤러 테스트 코드 작성
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/dto/response/FeedDto.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/entity/Feed.java
  src/main/java/com/codeit/sb01otbooteam06/domain/feed/repository/FeedQueryRepositoryImpl.java
  src/test/java/com/codeit/sb01otbooteam06/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/com/codeit/sb01otbooteam06/util/EntityProvider.java
Labels: ✅테스트 코드, ♻️리팩토링

#161 의상 서비스 코드 작성
  src/main/java/com/codeit/sb01otbooteam06/config/GeminiConfig.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/AttributeDefService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/JsoupService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/clothes/service/RecommendService.java
  src/main/resources/application.yml
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/service/AttributeDefServiceTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesAttributeServiceTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesCacheServiceTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/service/ClothesServiceTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/service/RecommendClothesServiceTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/clothes/service/RecommendServiceTest.java
  src/test/java/com/codeit/sb01otbooteam06/util/EntityProvider.java
  src/test/resources/application-test.yml
Labels: ✅테스트 코드

#185 test : user-profile 테스트 코드
  src/main/java/com/codeit/sb01otbooteam06/config/SecurityConfig.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/controller/AuthController.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/dto/MeResponse.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/dto/ResetPasswordRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/dto/SignInRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/dto/TokenResponse.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/service/AuthService.java
  src/main/java/com/codeit/sb01otbooteam06/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/codeit/sb01otbooteam06/domain/profile/entity/Profile.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/ChangePasswordRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/dto/UserCreateRequest.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/entity/User.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/init/AdminInitializer.java
  src/main/java/com/codeit/sb01otbooteam06/domain/user/service/UserServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/codeit/sb01otbooteam06/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/auth/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/auth/jwt/JwtTokenProviderTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/auth/service/AuthServiceImplTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/profile/controller/ProfileControllerTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/profile/repository/ProfileRepositoryTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/profile/service/ProfileServiceImplTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/codeit/sb01otbooteam06/domain/user/service/UserServiceImplTest.java
Labels: ✅테스트 코드

#199 리드미 업데이트
  README.md
Labels: ✏️문서작성
